### ISSUE TITLE
MiniRocket clarifications

### ISSUE THREAD

**Issue by tombh** [timeseriesAI/tsai#108]
I read and followed [the recent notebook about MiniRocket](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/10_Time_Series_Classification_and_Regression_with_MiniRocket.ipynb). Thank you very much for that. It certainly seems extremely fast. I've tried both the sklearn version and the pytorch version, I'm leaning more towards the pytorch version, though not because the sklearn version is too slow!

**RAM usage**
In order to avoid OOM on GPU I've found myself doing this:
```python
mrf.fit(X_train_torch[0:100, :, :])
X_feat = get_minirocket_features(X_train_torch, mrf, chunksize=128, to_np=True)
```
where `mrf.fit()` is only receiving 100 samples (samples are approx 3000 steps of 5 multivariate features) and chunksize is `128`. I assume chunksize is totally fine in terms of final output, but I worry that reducing the number of samples to `mrf.fit()` could be detrimental?

**Predictions for pytorch version**
Firstly I'm confused between the various load and save methods, namely between what's in the [model file](https://github.com/timeseriesAI/tsai/blob/0560fa5f0d5294f0c415c6da2296aee1c21a8904/tsai/models/MINIROCKET.py) and in the recent notebook. I think the load/save functions in the model file are for sklearn and the load_all/save_all functions in the notebook are for pytorch? I can't find any documentation on predicting with pytorch (other than through the fastai project), but I suspect there's more to it with MiniRocket anyway? For example should in fact `X_feat` be passed to the predictor? And how does `X` get normalised/standardised before being passed to predict? I assume that `learn.predict()` is the appropriate method, but even with the UCR data from the notebook it gives an error of:
```
File "/home/tombh/.cache/pypoetry/virtualenvs/mmt--DgCXr8U-py3.9/lib/python3.9/site-packages/fastai/layers.py", line 136, in Flatten
    return TensorBase(x.view(-1) if self.full else x.view(x.size(0), -1))
AttributeError: 'tuple' object has no attribute 'view'
```
I'm doing classification and I see that `learn.get_X_preds(X)` returns some results, but they're all floats, not labels.

Thanks for any advice ✨

**Comment by oguiza** [comment]
Hi @tombh,
Thanks a lot for your feedback.
I'm sorry for my late reply.
As to mrf.fit() step there's no need in general to reduce the number of samples that you pass. It's actually better not to reduce that number so that the model will randomly pick the ones it needs. Or is this throwing you an OOM error is you pass the entire train set?
Based on your comments on predictions I've updated the MiniRocket tutorial notebook. I think it's clearer now how you can save the model and generate predictions. It'd be great if you would review it and provide some feedback.

**Comment by tombh** [comment]
Hey @oguiza,

Thanks so much, that was exactly what I needed! I've got it working in offline and online mode and getting back the predictions I need. Also the OOM I was having with `mrf.fit()` hasn't even happened once.

I have a few more questions now, but they're not really showstoppers. Is `probas` the probability/confidence for each prediction? If so, how do I interpret them? For my setup I'm getting an error with `learn.show_probas()`:

```
File "/home/tombh/.cache/pypoetry/virtualenvs/mmt--DgCXr8U-py3.9/lib/python3.9/site-packages/fastai/data/load.py", line 94, in __len__
  return self.n//self.bs + (0 if self.drop_last or self.n%self.bs==0 else 1)
ZeroDivisionError: integer division or modulo by zero
```

Also, in theory can the `learner` be resumed? As in can I send it through more epochs with new data at a later date? Curiously I notice when I try that I get exactly the same error as above.

**Comment by vrodriguezf** [comment]
how are you creating the dataloaders that you pass to the learner? IT seems that your batch size is 0

**Comment by tombh** [comment]
Oh, it's my fault! I wasn't doing `learn.dls = dls` after loading the saved learner. So in theory it's ok to continue training a learner with new data at a later date?

That also means the `learn.show_probas()` function works now. Although it's not what I was looking for. Rather, is there a way to get an array of the probability/confidence associated with each individual prediction?

**Comment by oguiza** [comment]
Hi @tombh,

>Is probas the probability/confidence for each prediction?

The first output is always the raw network's output. For example, in a classification task, yes that's the sample's probability of each class (adding up to 1). You can interpret it as how certain the model is that the time series belongs to each class. In a regression task, it'd be the actual predicted value.

>For my setup I'm getting an error with learn.show_probas()

In fastai there are 2 groups of Learner methods that work differently (see docs [here](https://docs.fast.ai/learner.html#Learner.save)): 

- learn.save and learn.load: allow you to save a model and optimizer state. This allows you to resume training if needed. But if you close the session, you will need to instantiate the learner again, and do learn.load(). Then you'll have it in the same state as you left it, and can continue training. 
- learn.export and load_learner: allow you to save a trained model, the structure of the dataloaders (with an empty dataset), and without the optimizer state (so you can't resume training). The exported learner doesn't have any data. That's why you get the error message. It's only meant to be used to generate predictions. 

So if you want to do learn.show_probas, you must do that before exporting the model. And if you plan to resume training, you should learn.save it. You can use learn.load if the learner object is available, or create a new one. 

Here's a minimal code example: 

- Option 1: plan to retrain
```


X, y, splits = get_UCR_data('LSST', split_data=False)
tfms = [None, TSClassification()]
batch_tfms = TSStandardize(by_sample=True)
dls = get_ts_dls(X, y, splits, tfms=tfms, batch_tfms=batch_tfms)
learn = ts_learner(dls, InceptionTimePlus)
learn.fit_one_cycle(1)
learn.save('model0')
learn.show_probas()


# output
# epoch 	train_loss 	valid_loss 	time
# 0 	1.612553 	1.404200 	00:00
```
You can learn.show_probas(), or learn.show_preds(), or anything you want.
If you close the session but want to resume training, you'd do: 
```
del learn  # this is to simulate you are now in a different session

X, y, splits = get_UCR_data('LSST', split_data=False)
tfms = [None, TSClassification()]
batch_tfms = TSStandardize(by_sample=True)
dls = get_ts_dls(X, y, splits, tfms=tfms, batch_tfms=batch_tfms)
learn = ts_learner(dls, InceptionTimePlus)
learn.load('model0')
learn.validate()

#output
# (#1) [1.4042001962661743]
```

- Option 2: you are done with training, but want to use the model for inference in the future:  
```
X, y, splits = get_UCR_data('LSST', split_data=False)
tfms = [None, TSClassification()]
batch_tfms = TSStandardize(by_sample=True)
dls = get_ts_dls(X, y, splits, tfms=tfms, batch_tfms=batch_tfms)
learn = ts_learner(dls, InceptionTimePlus, metrics=accuracy)
learn.fit_one_cycle(1)
learn.export('test_export')
del learn

# output
# epoch 	train_loss 	valid_loss 	accuracy 	time
# 0 	1.638365 	1.347605 	0.604623 	00:01
```
When you need to recreate it, you'd do: 
```
learn = load_learner('./test_export')
learn.dls.dataset  # this is just to confirm the learner doesn't have any data

# output
# (#0) []
```
Now you are ready to create predictions: 
```
probas, _, preds = learn.get_X_preds(X[splits[1]])
```
And you can confirm the predictions are correct by doing this: 
```
skm.accuracy_score(y[splits[1]], preds)
# output
# 0.6046228710462287  # the output with the valid samples matches the accuracy when the model was trained .604623
```
I hope this is clearer now.

**Comment by tombh** [comment]
Ah right the probas shape includes the probability for each class, that was the insight I was missing. And yes that's totally clear now about the difference between the saved and exported learner. I've got everything I need working now! Thank you so much. I'll close this then.
