### ISSUE TITLE
How to do the inference with the TST (Transformer) ?

### ISSUE THREAD

**Issue by Scienceseb** [timeseriesAI/tsai#156]
Hello I'm currently able to train, save and load a TST model using my own data with the following code: 

```
bs=4
n_epochs=2

splits = RandomSplitter()(X)
tfms  = [None, [TSRegression()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid,bs=bs, batch_tfms=TSStandardize())


model = TST(dls.vars, dls.c, dls.len, res_dropout=0.1, fc_dropout=0)

learn = Learner(dls, model)
learn.fit_one_cycle(n_epochs, lr_max=1e-4)

PATH = Path('models/Regression.pkl')
learn.export(PATH) #save the model
model_for_inference= load_learner(PATH, cpu=False) #load the model
```

But I am currently unable to do inference using my model_for_inference because I just dont know what function to use. What I want to do is make predictions using model_for_inference on the validation dataset. 

Thanks a lot.

Kind regards,
Sébastien de Blois

**Comment by vrodriguezf** [comment]
You can use `learn.predict` to make inference to invidivual new items, or `learn.get_preds` to make it at the level of batches or entire dataloaders. fastai's documentation on [inference functions](https://docs.fast.ai/learner.html#Inference-functions) has more info about this.

**Comment by Scienceseb** [comment]
> You can use `learn.predict` to make inference to invidivual new items, or `learn.get_preds` to make it at the level of batches or entire dataloaders. fastai's documentation on [inference functions](https://docs.fast.ai/learner.html#Inference-functions) has more info about this.

I tried that before asking here : 
`model_for_inference.get_preds(dls.valid)`

I get the following error: 
`TypeError: list indices must be integers or slices, not TSDataLoader`

**Comment by Scienceseb** [comment]
> You can use `learn.predict` to make inference to invidivual new items, or `learn.get_preds` to make it at the level of batches or entire dataloaders. fastai's documentation on [inference functions](https://docs.fast.ai/learner.html#Inference-functions) has more info about this.

I am much more used to PyTorch than FastAI and TSAI, I feel like a sorcerer's apprentice.

I tried two variations (one of which is offered on the FastAI website):

```
model_for_inference = load_learner(PATH, cpu=False) #load le model

model_for_inference.get_preds()
preds,targs = model_for_inference.get_preds()
x,y = model_for_inference.dls.valid_ds.tensors
```

This give the error : 
`ZeroDivisionError: integer division or modulo by zero` at the line `model_for_inference.get_preds()`

```
model_for_inference = load_learner(PATH, cpu=False) #load le model

model_for_inference.get_preds(dls.valid)

```
This give the error: TypeError: list indices must be integers or slices, not TSDataLoader

**Comment by oguiza** [comment]
Hi @Scienceseb,
The easiest way to get predictions in `tsai` is to use: 
```
learn = load_learner(PATH, cpu=False) 
probas, _, press = learn.get_X_preds(X_test)
```
where X_test is a numpy array with the same format as X (used in training). 
Bear in mind that this is more than a model. The `learn` object has an empty dataloader with the required transforms (if any). That's why I don't call it model_for _inference.
Please, let me know if you have any issues with this approach.

**Comment by Scienceseb** [comment]
`

> probas, _, press = learn.get_X_preds(X_test)

So my X is in list format, this is working: 

`probas, _, press = learn.get_X_preds(np.asarray(X))`

But what exactly are the 3 outputs of get_X_preds ? 

Thanks a lot !

**Comment by Scienceseb** [comment]
> Hi @Scienceseb,
> The easiest way to get predictions in `tsai` is to use:
> 
> ```
> learn = load_learner(PATH, cpu=False) 
> probas, _, press = learn.get_X_preds(X_test)
> ```
> 
> where X_test is a numpy array with the same format as X (used in training).
> Bear in mind that this is more than a model. The `learn` object has an empty dataloader with the required transforms (if any). That's why I don't call it model_for _inference.
> Please, let me know if you have any issues with this approach.

So my X_test is in list format, this is working: 

`probas, _, press = learn.get_X_preds(np.asarray(X_test))`

But what exactly are the 3 outputs of get_X_preds ? 

Thanks a lot !

**Comment by oguiza** [comment]
The output changes depending on the task. 
I don't know if you are using it for classification,  regression, or anything else. 
preds, _, decoded_preds = learn.get_X_preds(np.asarray(X_test))
preds are the raw output predictions. In classification, they are the probabilities for each class. In regression, it's the raw predicted value. 
The 2nd term is None as we are not passing a y value. Otherwise, it'd be the target value for each prediction.
The 3rd term are the decoded predictions (once the applied transforms - if any-  are reversed). They may or may not be the same as the press (as you may or may not use batch transforms).
