### ISSUE TITLE
Perceiver model? 

### ISSUE THREAD

**Issue by TKassis** [timeseriesAI/tsai#161]
@oguiza I noticed you have a Perceiver model in the models directory. Going through the [paper ](https://arxiv.org/abs/2103.03206)it seems like a very promising model for multi-channel long sequences. Is there any reason why you don't mention it in the docs? I tried using the TSPerceiver model and was a bit disappointed. What has been your experience?

**Comment by oguiza** [comment]
Hi @TKassis,

Good catch! 

The reason why I haven't included it yet in the documentation is that I only include models that I have tested before. In the case of TSPerceiver, I'd still like to test it more thoroughly before documenting it. I don't have much experience to share yet, but I think it's a super-interesting concept to test. I'll use it as soon as I have a long-sequence dataset.

When you say you are a bit disappointed, what do you mean? You didn't achieve the desired performance? did you get OOM errors? or what? I'm curious to know about your experience with it. 

Another example of a model I have not yet documented is TSTransformerPlus. It's a transformer I've been using lately, that has worked pretty well for me. It's not a model from any particular paper, but a model I have created based on ideas from different papers. I will document it soon although I don't know what the value to others will be since it's not published.

**Comment by TKassis** [comment]
TSPerciever did not produce any errors, it worked quite well from an implementation perspective, but I guess the paper made it seem that it would be much better for time-series signals than other stuff out there. I've had much better performance with your TST implementation and even 1D ResNets.

**Comment by dnth** [comment]
I have also gotten better results with TSTPlus and other convolutional models. I noted that it trains slower than TST? Do you experience that?

**Comment by oguiza** [comment]
Hi @dnth,
Well, this is a model I'm experimenting with. I wouldn't recommend it for general use. I'd only use with long sequences. 
If you want to use a transformer with short time series, I'd rather use TSTPlus or TSTransformerPlus instead. 
One of the issues with Perceiver is that it introduces several new hyperparameters which make it more difficult to tune. I'm not sure the default hyperparameters work well.

**Comment by dnth** [comment]
I see.. just toying around at the moment.. really thankful that you're making this available!
