### ISSUE TITLE
How can I handle non-equi-length datasets with tsai

### ISSUE THREAD

**Issue by hno2** [timeseriesAI/tsai#175]
Hey everyone, 

thanks for the great toolbox you are providing!
One question that is currently bugging me is how to make tsai work with datasets, where each sample has different length. 
The UCR repository has some datasets that have varying length (e.g. `PLAID` or `PickupGestureWiimoteZ `). Do you usually just add padding to make them same length or how would you handle this?

Would love to see an example and more utilities for these usecases. 

Many Thanks!

**Comment by vrodriguezf** [comment]
I think it depends on your use case:

- If your dataset has samples with different length, but timesteps are evenly spaced, padding makes perfect sense. You can call [stack_pad](https://timeseriesai.github.io/tsai/utils.html#stack_pad) in a list of samples to add padding, or [SlidingWindowPanel](https://timeseriesai.github.io/tsai/data.preparation.html#SlidingWindowPanel) with a window size equals to the maximum length of a sample in your dataset, `stride=None`, and `pad_remainder=True`. You can even enable `add_padding_feature=True` to add a data channel indicating whether the time step is real or padded.

- If time steps are not evenly spaced, a.k.a irregular time series, you can try to make it regular with `add_missing_timestamps`, but you'll have to deal with the missing values created in that process. Another option is to add the timestamp information as a data channel (you can play with [time_encodings](https://timeseriesai.github.io/tsai/data.preparation.html#time_encoding) for this), and pad the sequences as in the previous case. In these cases you may want to use an attention based architecture (transformers) since the concept of "local connectivity" that convolutions rely on does not apply if timesteps can be further from each other in different samples.

**Comment by oguiza** [comment]
Thanks for your great and thorough reply to this issue  @vrodriguezf!
I will close this now due to a lack of response. Please, feel free to reopen if necessary.

**Comment by GodFire6666** [comment]
Thanks a lot guys, this really helps

**Comment by Victordmz** [comment]
The default value for `stack_pad` is `nan`, however, nan values do not work with this library. Is 0 a viable option then? Or does it depend on the model?

**Comment by oguiza** [comment]
Hi @Victordmz, please, don't use a closed issue to log a new (related one) since I cannot track it properly. You should create a new issue instead. You can reference this one if you want (adding #175).
