### ISSUE TITLE
Clarification on MultiInceptionTimePlus

### ISSUE THREAD

**Issue by TKassis** [timeseriesAI/tsai#183]
I'm trying to understand a bit more what the [MultiInceptionTimePlus](https://timeseriesai.github.io/tsai/models.InceptionTimePlus.html#MultiInceptionTimePlus) class does. Is this for example used when some of the features are not synced in time and hence need to be treated separately by a different InceptionTime branch and then the latent representations are concatenated before the final head?

A more concrete example. I have let's say 7 waveform features that are synced in time, but an additional 8th feature that describes the sample somehow but not related in time with the other 7 features. Could one use MultiInceptionTimePlus for this with:

feat_list = [[0, 1, 2, 3, 4, 5, 6], [7]]

Thanks,

**Comment by oguiza** [comment]
Exactly, @TKassis. You got it!

You can use MultiInceptionTimePlus whenever you need to process time series (or groups of time series) independently from others for whatever reason. The most frequent one as you mention is that they are on different time scales.

**Comment by TKassis** [comment]
@oguiza that's a great implementation! You've truly built the best time-series library out there. Everything else I've seen is miles behind :-)

**Comment by oguiza** [comment]
Wow! Thank you @TKassis! That is the best compliment I have ever received on `tsai`! 😃

I can just say `tsai` is the library I use in my own consulting work. I couldn't find any library that did what I wanted, so I decided to build my own.  I constantly find scenarios that require a different approach. That's why it's under active development.
