### ISSUE TITLE
Creating DataLoaders from multiple files

### ISSUE THREAD

**Issue by benihime91** [timeseriesAI/tsai#208]
Hi,
I am working on sort of a time series problem. So my files my stored in individual  `.npy` files. The sturucture would look something like this 

```
files
|-train
|   |-00.npy
|   |-01.npy
|   |-02.npy
|
|-valid
|   |-00.npy
```
and a corresponding csv which contrains the file path and the targets associated with the samples. How can I create a `dataloaders` object from this other than creating a `dataloaders` object from a `TorchDataset` ?

**Comment by TKassis** [comment]
This might help #179

**Comment by benihime91** [comment]
For now this is what I did
```
def load_np_array(id_):
    x = np.load(id_)
    return x
    
dblock = DataBlock(blocks=(TSTensorBlock, CategoryBlock),
                   splitter=ColSplitter(),
                   get_x=Pipeline([ColReader(2), load_np_array]),
                   get_y=ColReader(1),
                   item_tfms=None,)

dls = dblock.dataloaders(df, bs=256, val_bs=512, num_workers=8)
```

Is this approach correct ?

**Comment by oguiza** [comment]
Hi @benihime91,

Thanks for raising this important question. Since it's a recurring question that I get, I've prepared a small gist containing 5 options with some dummy data that I've created (I hope it's close enough to your dataset).

The first option is the one you shared before. There's nothing wrong with that type of approach. It's actually the native way of doing it in fastai. You can use it. 

However, I found that approach very slow, especially for large datasets. This is actually one of the reasons why I decided to create ´tsai`. I've shared 4 additional approaches you could use, that are 2-4 x faster using `tsai`. 

Please, try them and let me know what you think. If this is useful, I will prepare a tutorial notebook. 

Here's the [gist](https://colab.research.google.com/gist/oguiza/fba045c98f537bcee543dc36ae3397ca/scratchpad.ipynb).

**Comment by oguiza** [comment]
I'll close this issue due to a lack of response. Please, reopen if necessary.
