### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by maheshs11** [timeseriesAI/tsai#296]
![image](https://user-images.githubusercontent.com/7268915/144626747-d114fd68-9968-4fb7-9c18-985371747749.png)
after changing to loss_func=CrossEntropyLossFlat()

**Comment by bob-mcrae** [comment]
I'm not sure why this issue is closed, as I think it's still pending and reproducible.  I raised this issue in: https://github.com/timeseriesAI/tsai/issues/283#, but this issue is accurate to the existing limitation in fastai, which I think tsai could overcome.  I have a working solution that I will post here, based on @oguiza's feedback.

**Comment by maheshs11** [comment]
> I'm not sure why this issue is closed, as I think it's still pending and reproducible. I raised this issue in: #283, but this issue is accurate to the existing limitation in fastai, which I think tsai could overcome. I have a working solution that I will post here, based on @oguiza's feedback.

this issue happened because i exported the model and loaded the model , if after training  i run it works no error so i closed.

**Comment by oguiza** [comment]
I believe this issue only occurs when using tsai 0.2.23 (pip install) but not when installing from GitHub. I'm planning to create a new release probably tomorrow to fix this and other issues.
