### ISSUE TITLE
How to use learner.get_X_preds with MultiInputNet for inference?

### ISSUE THREAD

**Issue by TKassis** [timeseriesAI/tsai#352]
Was wondering if anyone else is having this issue. I don't seem to be able to find a way for inference on MultiInputNet models. The 
 learner.get_X_preds() works great when using a single model but there doesn't seem to be a way to pass multiple inputs for a model created using MultiModalNet. Here is a super abbreviated version of where this doesn't work:

```python
X_1, y, splits = combine_split_data([X_train_1, X_valid_1], [y_train_1, y_valid_1])
dsets_1 = TSDatasets(X_1, y)
dls_1 = TSDataLoaders.from_dsets(dsets_1.train, dsets_1.valid)

X_2, y, splits = combine_split_data([X_train_2, X_valid_2], [y_train_2, y_valid_2])
dsets_2 = TSDatasets(X_2, y)
dls_2 = TSDataLoaders.from_dsets(dsets_2.train, dsets_2.valid)

model_1 = build_ts_model(arch=InceptionTimePlus, c_in=dls_1.vars, c_out=dls_1.c, seq_len=dls_1.len, dls=dls_1)
model_2 = build_ts_model(arch=InceptionTimePlus, c_in=dls_2.vars, c_out=dls_2.c, seq_len=dls_2.len, dls=dls_2)
MultiModalNet = MultiInputNet(model_1, model_2)

mixed_dls = get_mixed_dls(dls_1, dls_2, bs=8)

learn = Learner(dls=mixed_dls, model=MultiModalNet, metrics=[mae, rmse])

learn.fit(100, 1e-3)

```

Is there a way to load the validation sets from the mixed_dls loader such as:
```python
probas , targets, preds = learn.get_X_preds(mixed_dls.valid.X, mixed_dls.valid.y)
```
Thanks!

**Comment by oguiza** [comment]
Hi @TKassis,
you won’t be able to use learn.get_X_preds with MultiInputNet since it only accepts X and optionally y. learn.get_X_preds is just a convenience function that creates a new dataloader with X (and y).
In your case, you’ll need to build a new mixed dataloader with the new data, and use learn.get_preds(dl=new_mixed_dl).
Please, let me know if you have any problems with this approach.

**Comment by TKassis** [comment]
Thanks for clarifying, this sounds good!
