### ISSUE TITLE
Autoformer

### ISSUE THREAD

**Issue by celtics1863** [timeseriesAI/tsai#401]
I wonder if you are interested in this newest time series auto-regression model? For recently I reproduce autoformer for some reason and I have an idea to contribute my code to this repository.  If you need it, I wonder what should I do , besides adding a "autoformer.py" file in "tsai/models/".  The model relies on pytorch and einops only.    

Paper : [Autoformer](https://arxiv.org/abs/2106.13008)  

metric in ETTm:  
- Official Informer: MAE: 0.36 mse:0.239   
- Official Autoformer MAE: 0.301 mse:0.218  
- My Autoformer MAE: 0.291 mse:0.184

**Comment by oguiza** [comment]
Hi @celtics1863,
Thanks for your interest in adding Autoformer to tsai. 
I've looked at the paper and it seems a really interesting model. I'd love to add it to the library.
tsai is a library built using nbdev. I don't know if you are familiar with it. That means you actually create the code in jupyter notebooks. You also add some tests and documentation. This allows to automatically perform CI (continuous integration tests) as well as having the documentation generated automatically. [Here's](https://github.com/timeseriesAI/tsai/blob/main/nbs/124_models.TSiTPlus.ipynb) an example of TSiTPlus ( a transformer model I added some time ago).  
I created a CONTRIBUTING.mg guide to explain the steps you should take. 
We should also agree on the model's API. In tsai all arguments are very similar across models, which makes it easier to use for end-users.
And optionally, you could create a tutorial notebook (that you would sign) showing how to use the model on a particular task. 
I can help you throughout this process. The important thing is to have the code and align the arguments so that it works well with the rest of the library.
PS. I've seen you've used einops, which is not currently a dependency of tsai's (although I'm considering using it, but I'm currently trying to reduce dependencies as much as I can). How difficult would it be to get rid of einops in your model?

**Comment by celtics1863** [comment]
Thank you for your timely reply. Surely, einops can be get rid of. It's only for simplify some "torch.permute" operations.
Actually, I not familiar with nbdev :) so I will spend some time to start with it. 
I think, I firstly need to excute CONTRIBUTING.mg step by step. 
I will also refer to your TSiTPlus and try to complete a notebook.
After completing this two things, I will pull requests code.
I guess it is the right procedure, is it? Because I'm new to tsai, maybe I still need your help in this process. :)

**Comment by oguiza** [comment]
> After completing this two things, I will pull requests code.

The CONTRIBUTING.md doc will actually guide you as to how you need to create the PR.

> Because I'm new to tsai, maybe I still need your help in this process. :)
Sure, I'll be more than happy to help!

**Comment by oguiza** [comment]
Hi @celtics1863,
I'm still waiting for a reply to my PR comment. I reviewed your PR but couldn't find the Autoformer model. I wonder if you have any issues following the Contributing.md instructions. 
Could you please let me know the status of the PR? Are you planning to resubmit a new PR?
Thanks

**Comment by celtics1863** [comment]
> Hi @celtics1863, I'm still waiting for a reply to my PR comment. I reviewed your PR but couldn't find the Autoformer model. I wonder if you have any issues following the Contributing.md instructions. Could you please let me know the status of the PR? Are you planning to resubmit a new PR? Thanks

yes,sure.  I have been busy lately and will submit a new PR soon.

**Comment by oguiza** [comment]
Ok, great. Take your time. Just che king if there was any misunderstanding.

**Comment by oguiza** [comment]
Closed issue due to lack of activity.
