### ISSUE TITLE
Can't find the package tsai 

### ISSUE THREAD

**Issue by zmce2018** [timeseriesAI/tsai#531]
Hi all, 

I have found this error after I implement it from tsai.all import *. The package was installed properly and working perfectly normal. It became an error after the second time running.

**Comment by oguiza** [comment]
Hi @zmce2018, 
Could you please detail the steps and code you used? I’d like to reproduce the error. 
Also please copy the full traceback and paste it here between 3 backticks (```).

**Comment by zmce2018** [comment]
Hi @oguiza  

Many thanks for your reply. After 

````
from tsai.all import ContextManagers, mae,rmse,ShowGraph, InceptionTimePlus,combine_split_data,set_seed,check_data,TSRegressor,TSStandardize,get_ts_dls,ts_learner
Traceback (most recent call last):

  Input In [2] in <cell line: 1>
    from tsai.all import ContextManagers, mae,rmse,ShowGraph, InceptionTimePlus,combine_split_data,set_seed,check_data,TSRegressor,TSStandardize,get_ts_dls,ts_learner

  File F:\CNNpred\tsai.py:8 in <module>
    from tsai.all import ContextManagers, mae,rmse,ShowGraph, InceptionTimePlus,combine_split_data,set_seed,check_data,TSRegressor,TSStandardize,get_ts_dls,ts_learner

ModuleNotFoundError: No module named 'tsai.all'; 'tsai' is not a package
````

**Comment by zmce2018** [comment]
When I was doing fine tuning using the optuna, I have found the issue: 

```
[I 2022-06-01 13:36:38,938] Trial 62 pruned. Exception occured in `FastAIV2PruningCallback` when calling event `after_fit`:
	Trial was pruned at epoch 1.
```

**Comment by oguiza** [comment]
Hi @zmce2018,
Thanks for providing additional details. I now see what the issue is.
When you do ```from x import y, z``` x is expected to be a module and y and z python objects within that module.
```tsai.all``` is a module is tsai. So that's correct. But it doesn't contain any objects. It just imports all modules in tsai. That's why you get those errors. So you have 2 options:

* **Option 1**:
   ```python
   from tsai.all import *
   ```
    or a more restricted option: 
   ```python
   from tsai.basics import *
   ```
   I normally use this option when I'm working on a notebook and want to run some experiments.

* **Option 2**: 
   If you don't want to use the wild card *, you can do the following:
   ```python
   from fastcore.xtras import ContextManagers
   from tsai.metrics import mae, rmse
   ...

   ```
   I've used this option when I want to create a script and don't want to use *.

**Comment by oguiza** [comment]
> When I was doing fine tuning using the optuna, I have found the issue:
> 
> ```
> [I 2022-06-01 13:36:38,938] Trial 62 pruned. Exception occured in `FastAIV2PruningCallback` when calling event `after_fit`:
> 	Trial was pruned at epoch 1.
> ```

If this is a new issue, please create a separate one. Make sure you add all details to allow us to reproduce the issue.

**Comment by zmce2018** [comment]
Thank you @oguiza for your answer. Option 2 is a very good one. I will close this question.
