### ISSUE TITLE
output nan

### ISSUE THREAD

**Issue by CHonChou** [timeseriesAI/tsai#572]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/48724350/187480951-438d3013-ea05-4eff-9cd3-d122ede56e79.png">

Hi, when I train the regression model using tsai, I get nan output on my own data, but when I change the arch to TSTPlus the result is normal again. Looking forward to receiving your reply!

**Comment by vrodriguezf** [comment]
What about InceptionTimePlus?

**Comment by 123mitnik** [comment]
it happens to me when i set the device="cpu"  
(i need to set it to cpu - because of ```the MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 486400 bytes```)

**Comment by oguiza** [comment]
Hi @123mitnik,
I've never seen that issue before. Could you please post a short code snippet to try and reproduce this error?

**Comment by 123mitnik** [comment]
@oguiza  Hi Ignacio,

This is from pytorch. So, it has nothing to do with tsai - https://github.com/pytorch/pytorch/issues/86152

This is just because I can't run it with the nightly build of pytorch (where m1 apple silicon is supported). Tsai is not yet compatible with it (some printing issues - but I never had time to dig into it), so i'm running it on CPU. As for the @CHonChou issue - the nans may be coming from -inf values or nan inside the dataset.

**Comment by oguiza** [comment]
Once Pytorch and fastai fully support the new apple chips we'll make tsai compatible as well. 
But I'm afraid there's not much we can do for now.
