### ISSUE TITLE
Transformation Library

### ISSUE THREAD

**Issue by firmai** [timeseriesAI/tsai#578]
It would be great if there could be an option where we can install a small set of the library `pip install tsai[process-tools]` for those who only work with the process library and not with PyTorch and FastAI. 

For example, currently I am relying only on the SlidingWindowPanel function and a few other tools. 

Thanks for the great library.

**Comment by oguiza** [comment]
Thanks for sharing this idea @firmai!
I'm glad you find the data processing part useful.
Unfortunately, there's no simple way to do that (create a separate pip package). I'm afraid the only option is to install the entire library and just use the modules you find useful (I guess that's what you are doing).
I'll close this issue since it's something that cannot be fixed.
