### ISSUE TITLE
How to implement RNNs + Attention?

### ISSUE THREAD

**Issue by Waterkin** [timeseriesAI/tsai#595]
Maybe we can add attention module to RNNPlus.

**Comment by oguiza** [comment]
Hi @Waterkin,
Thanks for your suggestion.
We didn't include them when we added RNNPlus because they didn't show much improvement in [LSTM Fully Convolutional Networks
for Time Series Classification](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8141873). 
But more recent papers may show the benefit of adding attention to RNNs.
@Waterkin, would you like to submit a PR? Anybody else?

**Comment by oguiza** [comment]
Hi @Waterkin,
I've just merged a PR that @yangtzech has been so king to create (Thanks yangtzech!!).
You can see how it can be used in this [gist](https://colab.research.google.com/gist/oguiza/b0bea2305b44455845199e022bb7b32c/scratchpad.ipynb).
Based on this I'll close this long-standing issue.
