### ISSUE TITLE
How to carry out multi classification training

### ISSUE THREAD

**Issue by shushan2017** [timeseriesAI/tsai#70]
I tested a dataset of 4-classification, but failed

#===================================
import tsai
from tsai.all import *
print('tsai       :', tsai.__version__)
print('fastai     :', fastai.__version__)
print('fastcore   :', fastcore.__version__)
print('torch      :', torch.__version__)

X, y, splits = get_UCR_data('DiatomSizeReduction', return_split=False)
tfms  = [None, [Categorize()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=64, batch_tfms=TSStandardize(by_var=True))
model = TST(dls.vars, dls.c, dls.len, res_dropout=0.3, fc_dropout=0.9)
learn = Learner(dls, model, loss_func=LabelSmoothingCrossEntropyFlat(), 
                metrics=[RocAucBinary(), accuracy],  cbs=ShowGraphCallback2())
learn.fit_one_cycle(100, 1e-4) 
#=================================================
error：
ValueError: multi_class must be in ('ovo', 'ovr')

thanks！！！！！

**Comment by williamsdoug** [comment]
Your problem is the inclusion of RocAucBinary() as one of the metrics.
Changing metrics to metrics=[accuracy] works on my machine.

Working code:

X, y, splits = get_UCR_data('DiatomSizeReduction', return_split=False)
tfms = [None, [Categorize()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=64,
batch_tfms=TSStandardize(by_var=True))
model = TST(dls.vars, dls.c, dls.len, res_dropout=0.3, fc_dropout=0.9)
learn = Learner(dls, model, loss_func=LabelSmoothingCrossEntropyFlat(),
                metrics=[accuracy], cbs=ShowGraphCallback2())
learn.fit_one_cycle(100, 1e-4)

**Comment by shushan2017** [comment]
@ williamsdoug 
thank you !very very!!!!!

**Comment by oguiza** [comment]
Thanks, @shushan2017  for your question, and @williamsdoug for your quick reply!
Just some additional information.
If you really want to use RocAuc in multiclass problems, you should use RocAuc() instead of RocAucBinary(). This last one is just for binary classification problems. In your case, your dataset has 4 classes, so it's multiclass.

**Comment by williamsdoug** [comment]
@shushan2017  If you need to compute roc_auc, fastai includes  RocAucMulti as an alternative to RocAucBinary.  One limitation is that RocAucMulti appears to fail if more that 1 label is true.  

I'm currently using the following work-around:

        from sklearn.metrics import roc_auc_score as _roc_auc_score
        def roc_auc_multi(inp, targ, thresh=0.5, sigmoid=True):
            "Alternative roc_auc for instances when multiple tables are true"
            inp,targ = flatten_check(inp,targ)
            if sigmoid: inp = inp.sigmoid()
                
            np_inp = inp.detach().cpu().numpy()
            np_targ = targ.detach().cpu().numpy()
            
            return TensorBase(_roc_auc_score(np_targ, np_inp, average=None))

called as: 

   ...  metrics=[accuracy_multi, roc_auc_multi], ...

Note: Based on example in section  '3.3.2.15.3. Multi-label case' of the scikit-learn documentation
https://scikit-learn.org/stable/modules/model_evaluation.html#multilabel-ranking-metrics
