### ISSUE TITLE
Can you help adapt the latest models such as Crossformer?

### ISSUE THREAD

**Issue by Christoph-XJ** [timeseriesAI/tsai#779]
It would be great if some of the latest models could be adapted

**Comment by oguiza** [comment]
Hi  @Christoph-XJ,
I review papers on time series daily and know of Crossformer. However, due to our limited capacity to create/ adapt new models,  we need to select those that we really believe offer better performance.
While the architecture is certainly interesting, the performance doesn't seem to improve that of other models.
Having said that, there are contributors that occasionally propose to create a PR to add a new architecture. If you are interested, I can help you with the process.

**Comment by oguiza** [comment]
Closed due to lack of response.
